/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: haykel-shaba (https://sketchfab.com/haykel1993)
license: SKETCHFAB Standard (https://sketchfab.com/licenses)
source: https://sketchfab.com/3d-models/office-work-desk-lowpoly-bureau-game-assets-cf723624ef1c400b98f540532391c61a
title: OFFICE WORK DESK LOWPOLY BUREAU GAME ASSETS
*/

import React, { useEffect, useRef, useState } from 'react';
import { useLoader } from '@react-three/fiber';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader';
// import { EffectComposer } from '@react-three/postprocessing';

type GLTFResult = GLTF & {
  nodes: {
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
    mesh_51: THREE.Mesh
    mesh_52: THREE.Mesh
    mesh_53: THREE.Mesh
    mesh_54: THREE.Mesh
    mesh_55: THREE.Mesh
    mesh_56: THREE.Mesh
    mesh_57: THREE.Mesh
    mesh_58: THREE.Mesh
    mesh_59: THREE.Mesh
    mesh_60: THREE.Mesh
    mesh_61: THREE.Mesh
    mesh_62: THREE.Mesh
    mesh_0: THREE.Mesh
    mesh_5: THREE.Mesh
    mesh_6: THREE.Mesh
    mesh_7: THREE.Mesh
    mesh_8: THREE.Mesh
    mesh_9: THREE.Mesh
    mesh_10: THREE.Mesh
    mesh_11: THREE.Mesh
    mesh_12: THREE.Mesh
    mesh_13: THREE.Mesh
    mesh_14: THREE.Mesh
    mesh_15: THREE.Mesh
    mesh_16: THREE.Mesh
    mesh_17: THREE.Mesh
    mesh_18: THREE.Mesh
    mesh_19: THREE.Mesh
    mesh_20: THREE.Mesh
    mesh_21: THREE.Mesh
    mesh_22: THREE.Mesh
    mesh_23: THREE.Mesh
    mesh_24: THREE.Mesh
    mesh_25: THREE.Mesh
    mesh_26: THREE.Mesh
    mesh_27: THREE.Mesh
    mesh_28: THREE.Mesh
    mesh_29: THREE.Mesh
    mesh_30: THREE.Mesh
    mesh_31: THREE.Mesh
    mesh_32: THREE.Mesh
    mesh_33_2: THREE.Mesh
    mesh_34: THREE.Mesh
    mesh_33: THREE.Mesh
    mesh_36: THREE.Mesh
    mesh_37: THREE.Mesh
    mesh_38: THREE.Mesh
    mesh_39: THREE.Mesh
    mesh_40: THREE.Mesh
    mesh_41: THREE.Mesh
    mesh_42: THREE.Mesh
    mesh_43: THREE.Mesh
    mesh_44: THREE.Mesh
    mesh_45: THREE.Mesh
    mesh_46: THREE.Mesh
    mesh_47: THREE.Mesh
    mesh_48: THREE.Mesh
    mesh_49: THREE.Mesh
    mesh_50: THREE.SkinnedMesh
    mesh_63: THREE.Mesh
    mesh_64: THREE.Mesh
    mesh_65: THREE.Mesh
    mesh_66: THREE.Mesh
    mesh_67: THREE.Mesh
    mesh_68: THREE.Mesh
    mesh_69: THREE.Mesh
    mesh_70: THREE.Mesh
    mesh_71: THREE.Mesh
    mesh_72: THREE.Mesh
    mesh_73: THREE.Mesh
    mesh_74: THREE.Mesh
    mesh_75: THREE.Mesh
    mesh_76: THREE.Mesh
    mesh_77: THREE.Mesh
    GLTF_created_0_rootJoint: THREE.Bone
  }
  materials: {
    ['Material.003']: THREE.MeshBasicMaterial
    ['Material.003']: THREE.MeshBasicMaterial
    ['Material.004']: THREE.MeshBasicMaterial
    ['Material.001']: THREE.MeshBasicMaterial
    ['Material.002']: THREE.MeshBasicMaterial
    ['Material.006']: THREE.MeshBasicMaterial
    ['Material.008']: THREE.MeshBasicMaterial
    ['Material.004']: THREE.MeshBasicMaterial
    ['Material.007']: THREE.MeshBasicMaterial
    ['Material.009']: THREE.MeshBasicMaterial
  }
}

type ActionName = 'Animation'
type GLTFActions = Record<ActionName, THREE.AnimationAction>

export default function Model(props: JSX.IntrinsicElements['group']): React.ReactElement {
  const group = useRef<THREE.Group>();
  const gltf = useLoader(GLTFLoader, '/scene/room.glb');
  const { nodes, materials, animations } = gltf as GLTFResult;
  const [windowsColor, setWindowsColor] = useState<string>('#BFBEBE');
  const [windowsPointer, setWindowsPointer] = useState<boolean>(false);

  const materialWindows = materials['Material.002'].clone();

  useEffect(()=>{
    if(windowsPointer){
      materialWindows.setValues({color: 'rgb(250,250,80)'});
    }else {
      setWindowsColor(materials['Material.002'].color.getStyle());
    }
  }, [windowsPointer]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-1.5, 1.68, 4.49]} rotation={[0, 0.81, 0]} scale={[0.02, 0.02, 0.02]}>
            <group position={[-8.35, 10.11, 10.54]} rotation={[-Math.PI / 2, 0, 0]}>
              <group position={[0, -11.22, 0]}>
                <mesh
                  name="mesh_1"
                  geometry={nodes.mesh_1.geometry}
                  material={materials['Material.003']}
                  morphTargetDictionary={nodes.mesh_1.morphTargetDictionary}
                  morphTargetInfluences={nodes.mesh_1.morphTargetInfluences}
                />
              </group>
            </group>
            <group position={[0, 1.73, 7.62]}>
              <mesh geometry={nodes.mesh_2.geometry} material={materials['Material.003']} />
            </group>
          </group>
          <group position={[-1.58, 1.74, 4.44]} rotation={[-Math.PI / 2, 0, 0.81]} scale={[0.01, 0.01, 0.01]}>
            <mesh geometry={nodes.mesh_3.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-1.41, 1.71, 4.58]} rotation={[-1.96, 0.35, 2.45]} scale={[0.02, 0.02, 0.02]}>
            <group rotation={[0, 0, -Math.PI / 4]}>
              <mesh geometry={nodes.mesh_4.geometry} material={materials['Material.003']} />
            </group>
          </group>
          <group position={[-2.46, 3.02, -0.38]} rotation={[0, 0.05, 0.01]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_51.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-4.26, 1.45, 0.81]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_52.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-2.14, 3.66, 0.69]} rotation={[0, 0, 0]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_53.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-3.54, 3.74, 0.05]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_54.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-2.53, 2.65, 1.97]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_55.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-4.07, 3.8, 2.14]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_56.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-2.46, 3.02, -0.38]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_57.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-4.26, 1.45, 0.81]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_58.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-2.14, 3.66, 0.69]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_59.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-3.54, 3.74, 0.05]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_60.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-2.53, 2.65, 1.97]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_61.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-4.07, 3.8, 2.14]} scale={[0.52, 0.6, 0.52]}>
            <mesh geometry={nodes.mesh_62.geometry} material={materials['Material.004']} />
          </group>
          <group position={[-1.51, 1.36, 4.49]} rotation={[-Math.PI / 2, 0, 1.6]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.mesh_0.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.01, 2.27, 3.62]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.mesh_5.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.mesh_6.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-3.18, 4.01, 3.92]}>
            <mesh geometry={nodes.mesh_7.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.mesh_8.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-3.94, 3.6, 4.14]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 0.3, 0.3]}>
            <mesh geometry={nodes.mesh_9.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-3.96, 3.59, 3.89]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.mesh_10.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-3.96, 3.59, 3.88]} rotation={[Math.PI / 2, -0.91, 0]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.mesh_11.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-4.1, 2.41, 3.07]} scale={[0.82, 0.82, 0.82]}>
            <mesh geometry={nodes.mesh_12.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-4.12, 1.19, 3.85]} rotation={[Math.PI / 2, 0, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.mesh_13.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-4.35, 2.73, 3.93]} rotation={[Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_14.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-4.36, 2.41, 3.93]} rotation={[Math.PI / 2, -0.12, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_15.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-4.35, 2.06, 3.93]} rotation={[Math.PI / 2, -0.1, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_16.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-4.35, 1.71, 3.93]} rotation={[Math.PI / 2, 0, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_17.geometry} material={materials['Material.001']} />
          </group>
          <group position={[3.8, 2.41, 3.07]} scale={[0.82, 0.82, 0.82]}>
            <mesh geometry={nodes.mesh_18.geometry} material={materials['Material.001']} />
          </group>
          <group position={[3.77, 1.19, 3.85]} rotation={[Math.PI / 2, 0, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.mesh_19.geometry} material={materials['Material.002']} />
          </group>
          <group position={[3.67, 2.46, 3.93]} rotation={[Math.PI / 2, 0.02, 0]} scale={[0.06, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_20.geometry} material={materials['Material.001']} />
          </group>
          <group position={[4.23, 2.44, 3.93]} rotation={[Math.PI / 2, -0.13, 0]} scale={[0.06, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_21.geometry} material={materials['Material.001']} />
          </group>
          <group position={[4.09, 1.69, 3.93]} rotation={[Math.PI / 2, -0.09, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_22.geometry} material={materials['Material.001']} />
          </group>
          <group position={[3.98, 2.08, 3.93]} rotation={[Math.PI / 2, -0.02, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_23.geometry} material={materials['Material.001']} />
          </group>
          <group position={[3.97, 2.45, 3.93]} rotation={[Math.PI / 2, -0.14, 0]} scale={[0.05, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_24.geometry} material={materials['Material.001']} />
          </group>
          <group position={[3.87, 1.69, 3.93]} rotation={[Math.PI / 2, -0.12, 0]} scale={[0.06, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_25.geometry} material={materials['Material.001']} />
          </group>
          {
            //fenetre
          }
          <group position={[-2.8, 1.86, 2.75]} scale={[0.0425, 0.0228, 0.03]} onPointerEnter={() => setWindowsPointer(true)} onPointerLeave={() => setWindowsPointer(false)}>
            <mesh geometry={nodes.mesh_26.geometry} material={materialWindows} >
              <meshBasicMaterial
                attach="material"
                color={windowsColor}
                opacity={1}
                transparent
              />
 
            </mesh>
          </group>
          <group position={[-0.02, 3.8, 6.12]} scale={[0.03, 0.03, 0.27]}>
            <mesh geometry={nodes.mesh_27.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-3.56, 0.85, 5.06]} scale={[0.26, 0.29, 0.26]}>
            <mesh geometry={nodes.mesh_28.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-2.59, 0.87, 3.52]} rotation={[0, -0.2, 0]} scale={[0.27, 0.31, 0.27]}>
            <mesh geometry={nodes.mesh_29.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-1.45, 0.85, 4.49]} rotation={[0, 0.37, 0]} scale={[0.03, 0.03, 0.04]}>
            <mesh geometry={nodes.mesh_30.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-3.18, 0.54, 3.92]}>
            <mesh geometry={nodes.mesh_31.geometry} material={materials['Material.008']} />
          </group>
          {
            //Table issue
          }
          <group position={[-0.6, 1.42, 4.8]} rotation={[0, 0.24, 0]} scale={[0.003, 0.05, 0.05]}>
            <mesh geometry={nodes.mesh_32.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.52, 0.7, 4.22]} rotation={[0, 0.25, 0]} scale={[0.16, 0.16, 0.16]}>
            <mesh geometry={nodes.mesh_33_2.geometry} material={materials['Material.003']} />
          </group>
          <group position={[0.44, 1.01, 5.15]} rotation={[0, -1.04, 0]} scale={[0.04, 0.04, 0.04]}>
            <mesh geometry={nodes.mesh_34.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.51, 2.25, 3.9]} rotation={[Math.PI / 2, 0.02, 1.19]} scale={[0.03, 0.12, 0.03]}>
            <mesh
              name="mesh_33"
              geometry={nodes.mesh_33.geometry}
              material={materials['Material.003']}
              morphTargetDictionary={nodes.mesh_33.morphTargetDictionary}
              morphTargetInfluences={nodes.mesh_33.morphTargetInfluences}
            />
          </group>
          <group position={[1.02, 1.72, 4.16]} rotation={[0, 0.24, 0]}>
            <mesh geometry={nodes.mesh_36.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.68, 1.64, 4.4]} rotation={[0, -0.36, 0]}>
            <mesh geometry={nodes.mesh_37.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.69, 1.58, 4.4]} rotation={[0, -0.36, 0]}>
            <mesh geometry={nodes.mesh_38.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.63, 1.8, 4.16]} rotation={[1.49, -0.32, -1.83]} scale={[1, 1.19, 1]}>
            <mesh geometry={nodes.mesh_39.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.71, 1.79, 4.17]} rotation={[1.49, -0.3, -1.83]}>
            <mesh geometry={nodes.mesh_40.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.6, 1.32, 4.21]} rotation={[-Math.PI, 1.06, -Math.PI]} scale={[0.89, 1.07, 0.89]}>
            <mesh geometry={nodes.mesh_41.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.58, 1.07, 4.19]} rotation={[0, 0.25, 0]}>
            <mesh geometry={nodes.mesh_42.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.59, 0.72, 4.22]} rotation={[1.54, -0.11, -1.82]} scale={[0.84, 1, 0.84]}>
            <mesh geometry={nodes.mesh_43.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.67, 0.72, 4.25]} rotation={[1.55, -0.09, -1.82]} scale={[0.84, 0.77, 0.84]}>
            <mesh geometry={nodes.mesh_44.geometry} material={materials['Material.003']} />
          </group>
          <group position={[1.72, 0.69, 4.19]} rotation={[1.55, -0.07, -1.82]} scale={[0.71, 0.96, 0.71]}>
            <mesh geometry={nodes.mesh_45.geometry} material={materials['Material.003']} />
          </group>
          <group position={[3.5, 0.85, 4.6]} rotation={[0, 0, 0]} scale={[0.03, 0.03, 0.04]}>
            <mesh geometry={nodes.mesh_46.geometry} material={materials['Material.001']} />
          </group>
          <group position={[3.21, 1.38, 4.72]} rotation={[0, -0.01, 0]} scale={[0.03, 0.03, 0.03]}>
            <mesh geometry={nodes.mesh_47.geometry} material={materials['Material.003']} />
          </group>
          <group position={[2.37, 0.72, 4.08]} scale={[0.18, 0.18, 0.18]}>
            <mesh geometry={nodes.mesh_48.geometry} material={materials['Material.003']} />
          </group>
          <group position={[-0.09, 1.93, 4.18]} rotation={[-0.3, 0.48, 0.14]}>
            <mesh geometry={nodes.mesh_49.geometry} material={materials['Material.003']} />
          </group>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <group position={[-3.44, 0.4, 0.22]} rotation={[0, 1.51, 0]} scale={[0.52, 0.6, 0.52]} />
          <skinnedMesh
            geometry={nodes.mesh_50.geometry}
            material={materials['Material.004']}
            skeleton={nodes.mesh_50.skeleton}
          />
          {
            //background issue, change scale
          }
          <group position={[0.41, 1.24, -8.93]}>
            <mesh geometry={nodes.mesh_63.geometry} material={materials['Material.007']} scale={[5.,5.,5.]} />
          </group>
          <group position={[-0.14, 0.65, -6.36]} rotation={[0, -0.51, 0]} scale={[0.28, 0.28, 0.28]}>
            <mesh geometry={nodes.mesh_64.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-7.3, 1.86, 2.75]} scale={[0.0425, 0.0228, 0.03]}>
            <mesh geometry={nodes.mesh_65.geometry} material={materials['Material.002']} />
          </group>
          <group position={[5.03, 1.86, 2.75]} scale={[0.0425, 0.0228, 0.03]}>
            <mesh geometry={nodes.mesh_66.geometry} material={materials['Material.002']} />
          </group>
          <group position={[-7, 4.16, 3.25]} scale={[0.64, 0.12, 0.64]}>
            <mesh geometry={nodes.mesh_67.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-7, 0.34, 3.25]} scale={[0.64, 0.12, 0.64]}>
            <mesh geometry={nodes.mesh_68.geometry} material={materials['Material.001']} />
          </group>
          <group position={[7.71, 4.16, 8.21]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.64, 0.12, 0.64]}>
            <mesh geometry={nodes.mesh_69.geometry} material={materials['Material.001']} />
          </group>
          <group position={[-7.76, 4.16, 8.21]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.64, 0.12, 0.64]}>
            <mesh geometry={nodes.mesh_70.geometry} material={materials['Material.001']} />
          </group>
          <group position={[7.56, 0.65, -6.36]} rotation={[0, -0.51, 0]} scale={[0.28, 0.28, 0.28]}>
            <mesh geometry={nodes.mesh_71.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-8.08, 0.65, -6.36]} rotation={[0, -0.51, 0]} scale={[0.28, 0.28, 0.28]}>
            <mesh geometry={nodes.mesh_72.geometry} material={materials['Material.006']} />
          </group>
          <group position={[-15.97, 0.65, -6.36]} rotation={[0, -0.51, 0]} scale={[0.28, 0.28, 0.28]}>
            <mesh geometry={nodes.mesh_73.geometry} material={materials['Material.006']} />
          </group>
          <group position={[16.56, 0.65, -6.36]} rotation={[0, -0.51, 0]} scale={[0.28, 0.28, 0.28]}>
            <mesh geometry={nodes.mesh_74.geometry} material={materials['Material.006']} />
          </group>
          <group position={[0.39, 0.76, 2.75]} scale={[0.02, 0.02, 0.02]}>
            <mesh geometry={nodes.mesh_75.geometry} material={materials['Material.009']} />
          </group>
          <group position={[3.13, 0.54, 13.78]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.mesh_76.geometry} material={materials['Material.008']} />
            <mesh geometry={nodes.mesh_77.geometry} material={materials['Material.006']} />
          </group>
        </group>
      </group>
    </group>
  );
}
